version: '3.9'

services:
  track-it-azure-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer" # Means developer edition of Sql server
      MSSQL_MEMORY_LIMIT_MB: "1024"
    ports:
      - "1435:1433"
    volumes:
      - trackit-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "if ! timeout 10 bash -c '</dev/tcp/localhost/1433'; then exit 1; fi"]
      interval: 15s
      retries: 20
      start_period: 180s
      timeout: 20s
    networks:
      - trackit-network
    deploy:
      resources:
        limits:
          memory: 1.5GB
  
  track-it-backend:
    build:
      context: .
      dockerfile: TrackIt.Server/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      track-it-azure-sql-server:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - trackit-network

networks:
  trackit-network:
    driver: bridge

volumes:
  trackit-sql-data:
      