name: trackit-backend-ci-cd

on:
  push:
    branches: [ "main", "development" ]
    paths:
      - 'TrackIt.Server/**'
      - 'TrackIt.Core/**'
      - '*.sln'
  pull_request:
    branches: [ "main", "development" ]
    paths:
      - 'TrackIt.Server/**'
      - 'TrackIt.Core/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
      # Create server secrets JSON file from GitHub secret
    - name: Setup server user secrets
      run: |
        echo '${{ secrets.SERVER_SECRETS_JSON }}' > server_secrets.json
        dotnet user-secrets init --project TrackIt.Server
        dotnet user-secrets set --project TrackIt.Server --json "$(cat server_secrets.json)"
        rm server_secrets.json

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      # Create test secrets JSON file from GitHub secret  
    - name: Setup test user secrets
      run: |
        echo '${{ secrets.TEST_SECRETS_JSON }}' > test_secrets.json
        dotnet user-secrets init --project TrackIt.Api.IntegrationTests
        dotnet user-secrets set --project TrackIt.Api.IntegrationTests --json "$(cat test_secrets.json)"
        rm test_secrets.json

  docker-build-and-push:
      needs: build-and-test
      if: success() && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: TrackIt.Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/track-it-backend:latest
